// ── Known domains — authoritative map so Hunter always gets the right domain ──────
// These companies appear regularly in signals. Without this, Hunter gets skipped
// because Apollo can't always find a website for well-known private/public companies.
export const KNOWN_DOMAINS = {
  'USAA':                          'usaa.com',
  'Google':                        'google.com',
  'ADP':                           'adp.com',
  'Eli Lilly and Company':         'lilly.com',
  "Lowe's Companies, Inc.":        'lowes.com',
  "Lowe's":                        'lowes.com',
  'Hewlett Packard Enterprise':    'hpe.com',
  'Optum':                         'optum.com',
  'LHH':                           'lhh.com',
  'F&G':                           'fglife.com',
  'Colgate-Palmolive':             'colgatepalmolive.com',
  'Adobe':                         'adobe.com',
  'AMETEK':                        'ametek.com',
  'Authentic Brands Group':        'authenticbrandsgroup.com',
  'SRS Distribution':              'srsdistribution.com',
  'Kadant':                        'kadant.com',
  'Bakkt':                         'bakkt.com',
  'Allegiant':                     'allegiantair.com',
  'Allegiant Air':                 'allegiantair.com',
  'Sun Country Airlines':          'suncountry.com',
  'H.I.G. Capital':                'higcapital.com',
  'H.I.G':                         'higcapital.com',
  'Artivion':                      'artivion.com',
  'Nectar Social':                 'nectarsocial.com',
  'Radar':                         'radar.io',
  'Eisen':                         'eisen.ai',
  'Exaforce':                      'exaforce.com',
  'Armada':                        'armada.ai',
  'Stratos':                       'stratos.co',
  'GridCare':                      'gridcare.com',
  'Sidus Space':                   'sidusspace.com',
  'Endospan':                      'endospan.com',
  'Roadrunner':                    'roadrunnerwm.com',
  'Indicor':                       'indicorinstrumentation.com',
  'Molex':                         'molex.com',
  'Ferragamo':                     'ferragamo.com',
  'Hermeus':                       'hermeus.com',
  'FleishmanHillard':              'fleishmanhillard.com',
  'Sylogist':                      'sylogist.com',
  'MindBridge':                    'mindbridge.ai',
  'Salesforce':                    'salesforce.com',
  'salesforce':                    'salesforce.com',
  'ServiceNow':                    'servicenow.com',
  'servicenow':                    'servicenow.com',
  'Aptum':                         'aptum.com',
  'FDH Aero':                      'fdhaero.com',
  'Motivity':                      'motivity.net',
  'LGI Homes':                     'lgihomes.com',
  'AmplifyMD':                     'amplifymd.com',
  'Convective Capital':            'convectivecapital.com',
  'The Doux':                      'thedoux.com',
  'Widmer Brothers':               'widmerbrothers.com',
  'Verde AgriTech':                'verde.ag',
  'Perseus Mining':                'perseusmining.com',
  'Cielo':                         'cielotalent.com',
  'Hark':                          'hark.com',
  'Siris':                         'siris.com',
  'BRAMI':                         'eatbrami.com',
  'IREN':                          'iren.com',
  'FLINT':                         'flintanalytics.com',
  'VSXY':                          'vsxy.com',
  'Exa Labs':                      'exalabs.ai',
  'Strength of Nature':            'strengthofnature.com',
  'Brami Protein Pasta':           'eatbrami.com',
  'RemotePass':                    'remotepass.com',
  'Greenland Mines':               'greenlandmines.com',
  'Moment':                        'shopmoment.com',
  'S&P Global Ratings Maalot':    'spglobal.com',
  'Nourish':                       'nourishco.com',
  'ProphetX':                      'prophetx.co',
  'Boh':                           'bohtea.com',
  'Dust':                          'dust.tt',
};

export function getKnownDomain(companyName) {
  if (!companyName) return null;
  if (KNOWN_DOMAINS[companyName]) return KNOWN_DOMAINS[companyName];
  const lower = companyName.toLowerCase();
  for (const [k, v] of Object.entries(KNOWN_DOMAINS)) {
    if (k.toLowerCase() === lower) return v;
  }
  return null;
}
