[phases.setup]
aptPkgs = [
  "fonts-liberation",
  "libasound2t64",
  "libatk-bridge2.0-0t64",
  "libatk1.0-0t64",
  "libgbm1",
  "libgtk-3-0t64",
  "libnspr4",
  "libnss3",
  "libx11-xcb1",
  "libxcomposite1",
  "libxcursor1",
  "libxdamage1",
  "libxfixes3",
  "libxi6",
  "libxrandr2",
  "libxss1",
  "libxtst6",
  "xdg-utils",
  "ca-certificates",
  "wget",
  "unzip",
  "chromium-browser"
]

[phases.install]
cmds = ["npm ci"]

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
